version: '3.9'

services:
  clickhouse:
    container_name: reproducer-clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhousestorage:/var/lib/clickhouse
      - ./INIT_DB.sql:/docker-entrypoint-initdb.d/INIT_DB.sql

volumes:
  clickhousestorage: {}
